services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backy:latest 

  test:
    image: backy:latest
    volumes:
      - ./:/app
    working_dir: /app  
    command: go test ./...

